name: CDAwsPipeline

on:
  workflow_run:
    workflows: ["CIPipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull the Docker image
      run: sudo docker pull tuginone/server-firmware:latest

    - name: Delete old docker container
      run: sudo docker rm -f server-firmware || true

    - name: Create .env file
      run: |
        echo "URL_DB=${{ secrets.URL_DB }}" > .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

    - name: Run the Docker container with .env
      run: sudo docker run -d -p 4500:4500 --name server-firmware --env-file .env tuginone/server-firmware:latest
